[package]
name = "cch23-scandal47"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
shuttle-axum = "0.35.0"
shuttle-runtime = "0.35.0"
tokio = "1.28.2"
tracing = "0.1.40"
serde = {version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"

